export const ADMIN_GET_ALL_USER_DETAILS_REQUEST =
  'ADMIN_GET_ALL_USER_DETAILS_REQUEST';
export const ADMIN_GET_ALL_USER_DETAILS_SUCCESS =
  'ADMIN_GET_ALL_USER_DETAILS_SUCCESS';
export const ADMIN_GET_ALL_USER_DETAILS_FAILURE =
  'ADMIN_GET_ALL_USER_DETAILS_FAILURE';
export const ADMIN_GET_ALL_USER_DETAILS_RESET =
  'ADMIN_GET_ALL_USER_DETAILS_RESET';

export const ADMIN_IS_ADMIN_REQUEST = 'ADMIN_IS_ADMIN_REQUEST';
export const ADMIN_IS_ADMIN_SUCCESS = 'ADMIN_IS_ADMIN_SUCCESS';
export const ADMIN_IS_ADMIN_FAILURE = 'ADMIN_IS_ADMIN_FAILURE';
export const ADMIN_IS_ADMIN_RESET = 'ADMIN_IS_ADMIN_RESET';

export const ADMIN_IS_SUSPENDED_REQUEST = 'ADMIN_IS_SUSPENDED_REQUEST';
export const ADMIN_IS_SUSPENDED_SUCCESS = 'ADMIN_IS_SUSPENDED_SUCCESS';
export const ADMIN_IS_SUSPENDED_FAILURE = 'ADMIN_IS_SUSPENDED_FAILURE';
export const ADMIN_IS_SUSPENDED_RESET = 'ADMIN_IS_SUSPENDED_RESET';

export const ADMIN_DELETE_ALL_USER_DATA_REQUEST =
  'ADMIN_DELETE_ALL_USER_DATA_REQUEST';
export const ADMIN_DELETE_ALL_USER_DATA_SUCCESS =
  'ADMIN_DELETE_ALL_USER_DATA_SUCCESS';
export const ADMIN_DELETE_ALL_USER_DATA_FAILURE =
  'ADMIN_DELETE_ALL_USER_DATA_FAILURE';
export const ADMIN_DELETE_ALL_USER_DATA_RESET =
  'ADMIN_DELETE_ALL_USER_DATA_RESET';
