export const ADMIN_GET_ALL_USER_DETAILS_REQUEST =
  'ADMIN_GET_ALL_USER_DETAILS_REQUEST';
export const ADMIN_GET_ALL_USER_DETAILS_SUCCESS =
  'ADMIN_GET_ALL_USER_DETAILS_SUCCESS';
export const ADMIN_GET_ALL_USER_DETAILS_FAILURE =
  'ADMIN_GET_ALL_USER_DETAILS_FAILURE';
export const ADMIN_GET_ALL_USER_DETAILS_RESET =
  'ADMIN_GET_ALL_USER_DETAILS_RESET';
