export const AGENT_CHAT_REQUEST = 'AGENT_CHAT_REQUEST';
export const AGENT_CHAT_SUCCESS = 'AGENT_CHAT_SUCCESS';
export const AGENT_CHAT_FAILURE = 'AGENT_CHAT_FAILURE';
export const AGENT_CHAT_RESET = 'AGENT_CHAT_RESET';

