export const PROFILE_IMAGE_UPLOAD_REQUEST = 'PROFILE_IMAGE_UPLOAD_REQUEST';
export const PROFILE_IMAGE_UPLOAD_SUCCESS = 'PROFILE_IMAGE_UPLOAD_SUCCESS';
export const PROFILE_IMAGE_UPLOAD_FAILURE = 'PROFILE_IMAGE_UPLOAD_FAILURE';

//Memories images
export const MEMORY_IMAGE_UPLOAD_REQUEST = 'MEMORY_IMAGE_UPLOAD_REQUEST';
export const MEMORY_IMAGE_UPLOAD_SUCCESS = 'MEMORY_IMAGE_UPLOAD_SUCCESS';
export const MEMORY_IMAGE_UPLOAD_FAILURE = 'MEMORY_IMAGE_UPLOAD_FAILURE';

//Memories DELETE images
export const MEMORY_IMAGE_DELETE_REQUEST = 'MEMORY_IMAGE_DELETE_REQUEST';
export const MEMORY_IMAGE_DELETE_SUCCESS = 'MEMORY_IMAGE_DELETE_SUCCESS';
export const MEMORY_IMAGE_DELETE_FAILURE = 'MEMORY_IMAGE_DELETE_FAILURE';
