export const MEMORIES_GET_REQUEST = 'MEMORIES_GET_REQUEST';
export const MEMORIES_GET_SUCCESS = 'MEMORIES_GET_SUCCESS';
export const MEMORIES_GET_FAILURE = 'MEMORIES_GET_FAILURE';
export const MEMORIES_GET_RESET = 'MEMORIES_GET_RESET';

export const MEMORIES_CREATE_REQUEST = 'MEMORIES_CREATE_REQUEST';
export const MEMORIES_CREATE_SUCCESS = 'MEMORIES_CREATE_SUCCESS';
export const MEMORIES_CREATE_FAILURE = 'MEMORIES_CREATE_FAILURE';
