export const MEMORIES_GET_REQUEST = 'MEMORIES_GET_REQUEST';
export const MEMORIES_GET_SUCCESS = 'MEMORIES_GET_SUCCESS';
export const MEMORIES_GET_FAILURE = 'MEMORIES_GET_FAILURE';
export const MEMORIES_GET_RESET = 'MEMORIES_GET_RESET';

export const MEMORIES_CREATE_REQUEST = 'MEMORIES_CREATE_REQUEST';
export const MEMORIES_CREATE_SUCCESS = 'MEMORIES_CREATE_SUCCESS';
export const MEMORIES_CREATE_FAILURE = 'MEMORIES_CREATE_FAILURE';

export const MEMORIES_EDIT_REQUEST = 'MEMORIES_EDIT_REQUEST';
export const MEMORIES_EDIT_SUCCESS = 'MEMORIES_EDIT_SUCCESS';
export const MEMORIES_EDIT_FAILURE = 'MEMORIES_EDIT_FAILURE';

export const MEMORIES_DELETE_REQUEST = 'MEMORIES_DELETE_REQUEST';
export const MEMORIES_DELETE_SUCCESS = 'MEMORIES_DELETE_SUCCESS';
export const MEMORIES_DELETE_FAILURE = 'MEMORIES_DELETE_FAILURE';
